@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 主节点: 数据更新请求
主节点 -> 主节点: 加锁(cas)

alt 加锁成功 is false
  主节点 -> 客户端: 更新失败
else 加锁成功 is true
  主节点 -> 从节点: 新数据
  从节点 -> 从节点: 保证不存在半更新状态
  从节点 -> 主节点: ok
  主节点 -> 主节点: 等待收到半数或以上后更新自己并解锁，否则无限重试
  主节点 -> 客户端: 更新成功
end
@enduml